menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:basket_pk>', views.change_menu, name='change_menu'),
    path('menu/<int:menu_pk><int:category_pk>dish_<dish_pk_or_name><int:quantity>show_basket=<str:show_basket>show_similar=<str:show_similar>/', views.menu, name='menu'),
]

menu_assistant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls'))
]

menu/models.py
from django.db import models

# Create your models here.
class Ingredient(models.Model):
    """ can be in many dishes """
    name = models.CharField(max_length=30)
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Dish(models.Model):
    name = models.CharField(max_length=50)
    price = models.SmallIntegerField()
    ingredients = models.ManyToManyField(Ingredient)
    amount = models.SmallIntegerField()             # rename to quantity?
    is_available = models.BooleanField(default=True)
    portion_for = models.DecimalField(decimal_places=1, max_digits=2, default=0.7)
    similar = models.ManyToManyField('self',blank=True, null=True)
    # img = models.ImageField()

    class Meta:
        verbose_name_plural = "Dishes"

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30)
    dishes = models.ManyToManyField(Dish)
    description = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Menu(models.Model):
    # there must be one main menu and may be few specials
    name = models.CharField(max_length=60)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return str(self.name).lower()

class Dish_in_basket(models.Model):
    name = models.CharField(max_length=30)
    quantity = models.IntegerField()
    basket_pk = models.IntegerField(default=1)

    def __str__(self):
        return self.name

class Basket(models.Model):
    dishes = models.ManyToManyField(Dish_in_basket)

    class Meta:
        verbose_name_plural = "Basket"
    
    

menu/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Menu, Category, Dish, Dish_in_basket, Basket


# Create your views here.
def index(request):
    """ main page with logo, menu choice and account link in the future """
    menus = Menu.objects.all()
    
    # create new basket and save its pk in session
    basket = Basket()
    basket.save()
    basket_pk = basket.pk  
    request.session['basket_pk']=basket_pk

    context = {
        'menus' :   menus,
    }
    return render(request, 'menu/index.html', context)

def change_menu(request, basket_pk=None):
    """ main page with logo, menu choice and account link in the future """
    menus = Menu.objects.all()
    
    request.session['basket_pk']=basket_pk

    context = {
        'menus' :   menus,
    }
    return render(request, 'menu/index.html', context)

def menu(request, menu_pk=1, category_pk=1, dish_pk_or_name = '0', quantity = 0, show_basket=False, show_similar=False):
    """ all behavior of menu_view"""

    # set current menu and its categories
    menu = Menu.objects.get(pk=menu_pk) 
    categories = menu.categories.all()
    
    # set current category to display dishes, default is first cat of specific menu
    selected_category = Category.objects.get(pk=category_pk)
    dishes = list(selected_category.dishes.all())

    # to do: refactor attribute's types
    if dish_pk_or_name == '0':
        dish_pk_or_name = selected_category.dishes.first().pk


    basket_pk=request.session['basket_pk']

    # add to basket either from menu or from basket
    if quantity == 1: # I want to add to basket
        try:
            dish_pk_or_name = int(dish_pk_or_name) # it is dish_pk when we add from menu
            dish = Dish.objects.get(pk=dish_pk_or_name)
            if Dish_in_basket.objects.filter(name=dish, basket_pk=basket_pk): # if is in basket
                d = Dish_in_basket.objects.get(name=dish, basket_pk=basket_pk)
                d.quantity += 1
                d.save()  
            else:   # if not in basket
                Dish_in_basket.objects.create(name=dish, quantity=1, basket_pk=basket_pk)
           
        except:
            dish = Dish.objects.get(name=dish_pk_or_name) # it is dish_name when we add from basket
            d = Dish_in_basket.objects.get(name=dish, basket_pk=basket_pk)
            d.quantity += 1
            d.save()
            
    elif quantity == 2: # if I want to remove from basket
        dish = Dish.objects.get(name=dish_pk_or_name)
        d = Dish_in_basket.objects.get(name=dish, basket_pk=basket_pk)
        if d.quantity > 0:
            d.quantity -= 1
            d.save()
    else:
        try:
            dish = Dish.objects.get(pk=dish_pk_or_name)
        except:
            dish = Dish.objects.get(name=dish_pk_or_name)

    basket = Dish_in_basket.objects.filter(basket_pk=basket_pk)

    """ here is needed refactor - repeat yourself """
    # count number of dishes in basket
    count_dishes = []
    for dish_in_basket in basket:
        count_dishes.append(dish_in_basket.quantity)
    count_dishes = sum(count_dishes)

    # count number of pieces in basket
    count_pieces = []
    for dish_in_basket in basket:
        quantity = Dish.objects.get(name=dish_in_basket).amount
        how_many = dish_in_basket.quantity
        count_pieces.append(quantity * how_many)
    count_pieces = sum(count_pieces)
    
    # assume cost of basket
    count_costs = []
    for dish_in_basket in basket:
        price = Dish.objects.get(name=dish_in_basket).price
        how_many = dish_in_basket.quantity
        count_costs.append(price * how_many)
    count_costs = sum(count_costs)

    # count for how many people is food in basket
    count_portion = []
    for dish_in_basket in basket:
        portion = Dish.objects.get(name=dish_in_basket).portion_for
        how_many = dish_in_basket.quantity
        count_portion.append(portion * how_many)
    count_portion = int(round(sum(count_portion)))

    
    context =  {'menu'        :   menu,
                'categories'  :   categories,
                'category'    :   selected_category,
                'dish_pk_or_name'     :   dish_pk_or_name,
                'dish'        :   dish,
                'dishes'      :   dishes,
                'basket'      :   basket,
                'basket_pk'   :   basket_pk,   
                'count_dishes':   count_dishes,
                'count_pieces':   count_pieces,
                'count_costs' :   count_costs,
                'count_portion':  count_portion,
                'show_basket' :   show_basket,
                'show_similar':   show_similar,
                }
    return render(request, 'menu/menu.html', context)

menu/templates/menu/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="UTF-8">
        <title>Wybierz menu</title>

        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
        
        {% block head %}
        {% endblock head %}
    </head>
    <body>
        {% block content  %}

        {% endblock content %}
    </body>
</html>

menu/templates/menu/index.html
{% extends 'menu/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock head %}

{% block content %}
    <div id="container">
        <div id="account-opt"></div>

        <div id="main-logo">
            <img src="{% static 'img/sushi.svg' %}">
            <p>
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor...
     
        <nav id="menus-choice">
            {% for menu in menus %}
            <a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=menu.categories.first.pk dish_pk_or_name='0' quantity=0 show_basket=False show_similar=False %}"><div class="menus-btn btn">{{ menu }}</div></a>
            {% endfor %}
        </nav>
    </div>
{% endblock content %}

menu/templates/menu/menu.html
{% extends 'menu/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
    <script src="https://kit.fontawesome.com/ef5689f1f5.js" crossorigin="anonymous"></script>

{% endblock head %}

{% block content %}
    <div id="container">
        <div id="search-bar">1</div>

        <div id="filters">2</div>

        <div id="account-opt">3</div>

        <div id="categories">
            {% for category in categories %}
                <a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=category.pk dish_pk_or_name=dish_pk_or_name quantity=0 show_basket=show_basket show_similar=False %}"><button class="category sheet">{{ category }}</button></a>
            {% endfor %}
            <a href="{% url 'menu:change_menu' basket_pk %}"><button class="category sheet">Zmień menu</button></a>
        </div>

        <div id="dishes">
            {% for dish in dishes %}
                <button class="dish sheet">
                    <div class="dish-name">
                        {% if dish.is_available == False %}
                            <span><s style="color:rgba(128, 44, 44, 0.2)">{{ dish }}</s></span>
                        {% else %}
                            <span style="color:#ffffff;">{{ dish.name }}</span>
                        {% endif %}
                    </div>
                    <div class="dish-amount-price">
                        {% if dish.is_available == False %}
                            <span><s style="color:rgba(128, 44, 44, 0.2)">{{ dish.amount }}szt {{ dish.price }}zł</s></span>
                        {% else %}
                            <span>{{ dish.amount }}szt {{ dish.price }}zł</span>
                        {% endif %}
                    </div>      
                    <div class="dish-ingredient">
                        {% for ingredient in dish.ingredients.all %}
                            {% if ingredient.is_available == False %}
                                <span><s style="color:rgba(128, 44, 44, 0.2)">{{ ingredient }},</s></span>
                            {% else %}
                                {% if dish.is_available == False %}
                                    <span><s style="color:rgba(128, 44, 44, 0.2)">{{ ingredient }},</s></span>
                                {% else %}
                                    <span>{{ ingredient }},</span>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="dish-add">
                        {% if dish.is_available == True %}
                            <a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=category.pk dish_pk_or_name=dish.pk quantity=1 show_basket=show_basket show_similar=False %}">+</a>
                        {% endif %}
                    </div>
                </button>
            {% endfor %}
        </div>

        <div id="small-container">
            <div id="info-img">6</div>
            <div id="summary-extras">
                <div class="summary sheet">
                    <h1>Podsumowanie:</h1>
                    <ul>
                        <li>
                            <p class="count-basket">ilość potraw:<span>{{ count_dishes }}</span></p><hr>
                        </li>
                        <li>
                            <p class="count-basket">liczba sztuk:<span>{{ count_pieces }}</span></p><hr>
                        </li>
                        <li>
                            <p class="count-basket">zestaw dla ok:<span>{{ count_portion }} x <i class="fas fa-male"></i></span></p><hr>
                        </li>
                        <li>
                            <p class="count-basket">cena:<span>{{ count_costs }}zł</span></p><hr>
                        </li>
                    </ul>
                </div>
                <div class="similar-btn">
                    {% comment %} <a href="#">
                        <button onclick="openSimilar()" class="similar-btn sheet">Podobne</button>
                    </a> {% endcomment %}
                    {% if show_similar == "True" %}
                        <a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=category.pk dish_pk_or_name=dish_pk_or_name quantity=0 show_basket=False show_similar=False %}">
                                <button class="similar-btn sheet">Podobne</button>
                            </a>
                            <style>
                                .similar {
                                    display: block;
                                }
                            </style>
                    {% else %}
                        <a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=category.pk dish_pk_or_name=dish_pk_or_name quantity=0 show_basket=False show_similar=True %}">
                                <button class="similar-btn sheet">Podobne</button>
                            </a>
                            <style>
                                .similar {
                                    display: none;
                                }
                            </style>
                    {% endif %}
                </div>
                <div class="basket-btn">
                    {% if show_basket == "True" %} {# hide basket if its displayed #}
                        <a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=category.pk dish_pk_or_name=dish_pk_or_name quantity=0 show_basket=False show_similar=False%}">
                            <button class="basket-btn sheet">Koszyk</button>
                        </a>
                        <style>
                            .basket {
                                display: block;
                            }
                        </style>

                    {% else %}
                        <a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=category.pk dish_pk_or_name=dish_pk_or_name quantity=0 show_basket=True show_similar=False %}">
                            <button class="basket-btn sheet">Koszyk</button>
                        </a>
                        <style>
                            .basket {
                                display: none;
                            }
                        </style>
                    {% endif %}
                </div>
                <div class="basket sheet">
                    {% if show_basket == "True" %}
                        <p>Koszyk</p>
                        {% comment %} {% if dish %} {% endcomment %}
                            {% for dish in basket %}
                                <button class="dish-in-basket sheet">
                                    <div class="dish-name">{{ dish }}</div>
                                    <div class="dish-amount-price">{{ dish.quantity }}szt</div>
                                    <div class="dish-add"><a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=category.pk dish_pk_or_name=dish.name quantity=1 show_basket=show_basket show_similar=False %}">+</a></div>
                                    <div class="dish-remove"><a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=category.pk dish_pk_or_name=dish.name quantity=2 show_basket=show_basket show_similar=False %}">-</a></div>
                                </button>
                            {% endfor %}
                        {% comment %} {% endif %} {% endcomment %}
                    {% endif %}
                </div>
                <div id="similar" class="similar sheet">
                    {% if show_similar == "True" %}
                        <p>Podobne</p>
                        <p>{{ dish }}ddd</p>
                            {% for similar_dish in dish.similar.all %}
                                <button class="dish-in-basket sheet">
                                    <div class="dish-name">{{ similar_dish }}</div>
                                    <div class="dish-amount-price">{{ dish.quantity }}szt</div>
                                    <div class="dish-add"><a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=category.pk dish_pk_or_name=dish.name quantity=1 show_basket=show_basket show_similar=False %}">+</a></div>
                                    <div class="dish-remove"><a href="{% url 'menu:menu' menu_pk=menu.pk category_pk=category.pk dish_pk_or_name=dish.name quantity=2 show_basket=show_basket show_similar=False %}">-</a></div>
                                </button>
                            {% endfor %}
                    {% endif %}
                </div>
            </div> 
        </div>
    </div>
    <script src="{% static 'js/javascript.js' %}""></script> 
{% endblock content%}